"""修改用户表

Revision ID: bf94b497e4fa
Revises: 
Create Date: 2019-02-22 17:21:19.543429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf94b497e4fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthday', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('gender', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('moblie', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('nickname', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'moblie')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'email')
    op.drop_column('users', 'birthday')
    # ### end Alembic commands ###
